import { homedir } from 'node:os';
import { join } from 'node:path';
// Static JSON import, not a disk read at install time — `bun build --compile`
// packs this into the binary's virtual filesystem; a real file path wouldn't
// resolve at runtime (same constraint render.ts's runtime-bundle imports hit).
// Generated by scripts/build-skill.ts — run `bun run build:skill` after
// cloning before this resolves to anything real.
import skillContent from './generated/skill-content.json';

export async function installSkill(options: IInstallSkillOptions): Promise<string> {
	const root = options.target ?? join(options.global ? homedir() : process.cwd(), '.claude', 'skills', 'basemark');

	await Bun.write(join(root, 'SKILL.md'), skillContent.skillMd);
	for (const [name, content] of Object.entries(skillContent.references)) {
		await Bun.write(join(root, 'references', `${name}.md`), content);
	}

	return root;
}

export interface IInstallSkillOptions {
	global?: boolean;
	target?: string;
}
