import { mkdir, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
// Static JSON import, bundled at build time (see scripts/build.ts) so it
// resolves as a real value in the published dist/index.js, not a disk read.
// Generated by scripts/build-skill.ts — run `bun run build:skill` after
// cloning before this resolves to anything real.
import skillContent from './generated/skill-content.json';

async function writeFileDeep(path: string, content: string): Promise<void> {
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, content);
}

export async function installSkill(options: IInstallSkillOptions): Promise<string> {
	const root = options.target ?? join(options.global ? homedir() : process.cwd(), '.claude', 'skills', 'basemark');

	await writeFileDeep(join(root, 'SKILL.md'), skillContent.skillMd);
	for (const [name, content] of Object.entries(skillContent.references)) {
		await writeFileDeep(join(root, 'references', `${name}.md`), content);
	}

	return root;
}

export interface IInstallSkillOptions {
	global?: boolean;
	target?: string;
}
