// Runs before the main tsup build (see package.json's "build" script). Bakes
// theme.css, the four runtime IIFE bundles, and bio.css into a TS module of
// string constants — render.ts imports them as normal code instead of
// reading files off disk at runtime, so dist/index.js has no companions.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const themeCssPath = fileURLToPath(import.meta.resolve('@basemark/core/theme.css'));

const [themeCss, baseRuntimeJs, commonRuntimeJs, bioRuntimeJs, chartsRuntimeJs, bioCss] = await Promise.all([
	readFile(themeCssPath, 'utf-8'),
	readFile('src/generated/base.global.js', 'utf-8'),
	readFile('src/generated/common.global.js', 'utf-8'),
	readFile('src/generated/bio.global.js', 'utf-8'),
	readFile('src/generated/charts.global.js', 'utf-8'),
	readFile('src/generated/bio.css', 'utf-8'),
]);

const out = `// Generated by scripts/generate-assets.ts — do not edit by hand.
export const themeCss = ${JSON.stringify(themeCss)};
export const baseRuntimeJs = ${JSON.stringify(baseRuntimeJs)};
export const domainRuntime: Record<string, string> = {
	common: ${JSON.stringify(commonRuntimeJs)},
	bio: ${JSON.stringify(bioRuntimeJs)},
	charts: ${JSON.stringify(chartsRuntimeJs)},
};
export const domainCss: Record<string, string> = {
	bio: ${JSON.stringify(bioCss)},
};
`;

await writeFile('src/generated/assets.ts', out);
console.log('Wrote src/generated/assets.ts');
